language: csharp
solution: JimsBackgroundChanger.sln
deploy:
  provider: releases
  api_key:
    secure: e7r+gPTjXvtlH9X8z9Uoa/c94r+3AnitV/JTGZbdymnX0YSM5xS6yApdZRAc0wyZ0uNssSHuJ9mKNob9msREvdz9Et4W5lrZNKSs/6V1++mD1QYmsfPrGWafdHy2u7uEcgXDKhzf7R+s58d9G38F1jJ8H+njacFBksS1DiEeh1FqSBa4k9td7uoLSEn3sVFgbYLvsPmSZDo6DbBD2tw19kZqoXrPiNG6zFI6JUAlzwJHHf/VE4afGMNSZPy783dMjaHqakYOcCkwBZhPGUCy8HcWZsgJJ8LYtTCLTtz2yliB1Qr7qcwJw5lyky97Uk/7ZNb4V9soT5c61T2oF8fv0i8IIvxGcxTvAIAt9s3rDcKeLkv99RhpkZ2ZNr4fJiVLHGTgJ6FIA68/4FaP0evGYxs4zfgKZ3sMWbxcQZ8iuM8k+hk/feDnscCQ1l8MpH1n/vMy6paHfRpM9sUuMBckJLmtvl36MwxF7Ig4Ge5BP/qYT1h6GPe5A/rO0ighRxwTR/mjJR3qAxWy9u+clW3a6nLy8sS9iOGIhC2xqp/Cztn6QdLXVmoG1IWH4T+L/sIjReRBmFB0vUxEdhBPJcCOIWoJ65xL5JOgbf7iXPk8/9Rp9lZgUZ2TnlOrafpApLPC6ue4aH1RmrX82cGOK/KmAvk1xBnhHm9HZqehXzmNg5c=
  file: "JimsBackgroundChanger/bin/Release/JimsBackgroundChanger.exe"
  skip_cleanup: true
  on:
    repo: Jimver/jimsbackgroundchanger
    tags: true
    

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "e4cv1sca/hOzJMTg4smIKPfi51sKA3x2TTR+N0IhUkt77yjTEmrf9BJbcnucjj9nGpcPSEdVy6rCFoqmiFUiRRp2pW6p/ROxJNThqfTPv4KJaXmLqPEajWl/RU/eL/OYbghOAvV55rcPVs7qnWGcRTFMgXmzyvMV0+kOxxYimNaLrPM+xMAmVRwokMRJqWJeQh0ypreDihCmuoJV2jY/mIKy7wSmZnZnOpfkP24LMsDjiQw/U4TK+UuBYtsBCCyY9WuhfK6Hg6vBAp7N7lnCreNGNsQqNF/6k7sHfJ6L1h8l0Q+kcYa0mK5ET92Dm9XM6P7M3PAL+QYFCpI7hwSqQUPLRss3nsWcfjiPefkf8PaGA3YftbEyoiNOvhCkyyf6t9dvVaVP2pLPM8lRheHVoxqsIdhoDwjtcfQdkUYvCO++901ps8gm6Fln9I9nnrrA0u0Tx57kOpK87zg+cT9U5HkYiDRNOv59qLrNbuJKlTWwjpyEXuoz/LxAmTbWkMQD5AzgU/Mtf7tqaJ40lkpIwB0EJPAFt7VL+BcRLXQKrUlo374ZkGYGbM5aBkTeEwEv2nR9RaZeJotVT0RgbRIQrp50xnOIzxMIO5KBDAw2/6ZsZ2Xx0Wcheh/HDn02KFvmYCRuTwg5XXcloRPYGP2t/Riy1nCaIZ3lKlDGVawD1as="
   #nokfcpEGFlLp2A1/l3wwmJaR65dmjY3A4/niWCoYvK4pw/E8Xw26DGEX9+WhCd3g0C/5qIJ6TM8jjMMFarrQLlHg9uAkdumkO8aZ8OuY6GC49CVJCtDp90r6zRDVaQ6Ou6ZKjfWM2ypniYBXDWja6ztERGuOndWJy4N2WESAznJ2C8glQ9M0RnsjRRQkOznrW74Xzcd6pOk3ntO48iQx6KP0UZu5lpndQuV7A00PQvQ0YvZQyM+MGGUXfttFgyKzKQFOXVqIXkzwEs9S6ZHq8Ch8fmllRMv4p7U3VX33j1d2VaFxfTOJVu1UpzSycAKs0RlBGJqrPhAJvN0snEb2Ve437g1U54HzFZleYdns9H8SlCsXEc9aiCAVqs0TtYrZUIFGCFEebfR+sCeDqspuDZXAIh7Bc1WFkSA3wUIRUGE5hnl7nML/x1AqXOmt97TcdiF53cFgk4DIR/2kPyhugbTz4wifj8YQPTke63T2MtMdOYhdEUDN2AVw2H8XXru2tmn0aPOYGcaDL61j6uFnrMugRJqXw5XJSpV7JCWpdHtmT9v6o/w8225zaWNNJ02qqrMOVj7jy7IWXiEBSx0axBWiTfBrXQ7An3jSUdYKGBXyiSmz9RBpZpScFpIFhYc34pzNICPfqbciBmiN4jUKN6+if+8s/EkkVg34HhCK0/w="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "Jimver/jimsbackgroundchanger"
      description: "Build submitted via Travis CI, on coverity_scan branch"
    notification_email: jim.verheijde@hotmail.com
    build_command_prepend: "xbuild /p:Configuration=Release /t:Clean"
    build_command: "xbuild /p:Configuration=Release ./JimsBackgroundChanger.sln"
    branch_pattern: coverity_scan
    
install:
  - nuget restore JimsBackgroundChanger.sln
script:
  - xbuild /p:Configuration=Release ./JimsBackgroundChanger.sln
  - mono ./packages/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./JimsBackgroundChanger.Tests/bin/Release/JimsBackgroundChanger.Tests.dll
#  - mono ./packages/OpenCover.*/tools/OpenCover.Console.exe -register:user -target:"./packages/NUnit.ConsoleRunner.*/tools/nunit3-console.exe" -targetargs:"./JimsBackgroundChanger.Tests/bin/Release/JimsBackgroundChanger.Tests.dll" -output:"./coverage.xml"
#  - mono ./packages/Codecov.*/tools/codecov.exe -f "coverage.xml" -t 4b4666f3-dbf9-4798-988e-6533df907d44