language: csharp
solution: JimsBackgroundChanger.sln
deploy:
  provider: releases
  api_key:
    secure: e7r+gPTjXvtlH9X8z9Uoa/c94r+3AnitV/JTGZbdymnX0YSM5xS6yApdZRAc0wyZ0uNssSHuJ9mKNob9msREvdz9Et4W5lrZNKSs/6V1++mD1QYmsfPrGWafdHy2u7uEcgXDKhzf7R+s58d9G38F1jJ8H+njacFBksS1DiEeh1FqSBa4k9td7uoLSEn3sVFgbYLvsPmSZDo6DbBD2tw19kZqoXrPiNG6zFI6JUAlzwJHHf/VE4afGMNSZPy783dMjaHqakYOcCkwBZhPGUCy8HcWZsgJJ8LYtTCLTtz2yliB1Qr7qcwJw5lyky97Uk/7ZNb4V9soT5c61T2oF8fv0i8IIvxGcxTvAIAt9s3rDcKeLkv99RhpkZ2ZNr4fJiVLHGTgJ6FIA68/4FaP0evGYxs4zfgKZ3sMWbxcQZ8iuM8k+hk/feDnscCQ1l8MpH1n/vMy6paHfRpM9sUuMBckJLmtvl36MwxF7Ig4Ge5BP/qYT1h6GPe5A/rO0ighRxwTR/mjJR3qAxWy9u+clW3a6nLy8sS9iOGIhC2xqp/Cztn6QdLXVmoG1IWH4T+L/sIjReRBmFB0vUxEdhBPJcCOIWoJ65xL5JOgbf7iXPk8/9Rp9lZgUZ2TnlOrafpApLPC6ue4aH1RmrX82cGOK/KmAvk1xBnhHm9HZqehXzmNg5c=
  file: "JimsBackgroundChanger/bin/Release/JimsBackgroundChanger.exe"
  skip_cleanup: true
  on:
    repo: Jimver/jimsbackgroundchanger
    tags: true
    
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "NfYKnkBYsIvm6IGxauYhNeSdt2ypgmCgV90SgpErXQ4P3zaEI4+TpPt7uzcO1926l4HmyQmXhh8vhdXb4WCGJf8pSx7Kf4oQ9lFYNJLaeJQcOJRu8h5GSsIz9aCA2mdSEKToBubQ5B7i8IbsKXGaPdv1MKMrCWXa3Sazfpu24qZ0MMhUXbsapAzDEAVayghjqRwSocVQSmqP+tbX9qdJ4amX2CssjlhnzTB0TGmtS/c+milMB1dwN7ECZlZgfzWS+VlWjyrwVGVAiqL9bg7FPGIU6d2qMKtbuC3tM6CmO7OP1fEXfi5QraHQkbkShpz0tYk9zU3K34EX6NXNSxu3Ti306Z+e+ppj/jVLjOq6peq8Zj4ye4E7ebTTz+9zGFIFN/AW62OpIQzr9e4BV+CJ+AV5dbdxEgSG3tLXlSRhsirdz3VeZM39Pl/i/aZpsxs2GpTGmGm4MJxIB7NTpbutGAWjPIJnUCKVW4fiw7Adbyev0qfVldNHYYyW89ZvwmBD1LtePDhdC6zpArkb8TmSs3wWYK32+mDmwbj2ONYIxRn/5h6L5AsWP+65j8Na1kqVptRImGqpIQTAYPy/BYQsswtg7BQ4iC9ZAFfX5vYOs6Px5Xd+YRrJtxqbS5TpR810XguPWPoOhF84if7g1E2X3ijCfuq2T/lT6sd5auh/QNI="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "Jimver/jimsbackgroundchanger"
      description: "Build submitted via Travis CI"
    notification_email: jim.verheijde@hotmail.com
    build_command_prepend: "xbuild /p:Configuration=Release /t:Clean"
    build_command:   "xbuild /p:Configuration=Release /t:Rebuild"
    branch_pattern: coverity_scan
    
install:
  - nuget restore JimsBackgroundChanger.sln
  - sudo apt-get install gtk-sharp2
  - curl -sS https://api.nuget.org/packages/mono.cecil.0.9.5.4.nupkg > /tmp/mono.cecil.0.9.5.4.nupkg.zip
  - unzip /tmp/mono.cecil.0.9.5.4.nupkg.zip -d /tmp/cecil
  - cp /tmp/cecil/lib/net40/Mono.Cecil.dll .
  - cp /tmp/cecil/lib/net40/Mono.Cecil.dll /tmp/cecil/
  - git clone --depth=50 git://github.com/csMACnz/monocov.git ../../csMACnz/monocov
  - cd ../../csMACnz/monocov
  - cp /tmp/cecil/Mono.Cecil.dll .
  - ./configure
  - make
  - sudo make install
  - cd $TRAVIS_BUILD_DIR
script:
  - xbuild /p:Configuration=Release ./JimsBackgroundChanger.sln
  - export LD_LIBRARY_PATH=/usr/local/lib
  - mono --debug --profile=monocov:outfile=monocovCoverage.cov,+JimsBackgroundChanger ./packages/NUnit.ConsoleRunner.3.6.0/tools/nunit-console.exe --process=Single ./JimsBackgroundChanger.Tests/bin/Release/JimsBackgroundChanger.Tests.dll
  - monocov --export-xml=monocovCoverage monocovCoverage.cov
  - cat monocovCoverage.cov
  - ls monocovCoverage
  - REPO_COMMIT_AUTHOR=$(git show -s --pretty=format:"%cn")
  - REPO_COMMIT_AUTHOR_EMAIL=$(git show -s --pretty=format:"%ce")
  - REPO_COMMIT_MESSAGE=$(git show -s --pretty=format:"%s")
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_BRANCH
  - echo $REPO_COMMIT_AUTHOR
  - echo $REPO_COMMIT_AUTHOR_EMAIL
  - echo $REPO_COMMIT_MESSAGE
  - echo $TRAVIS_JOB_ID
  - mono ./packages/coveralls.net.0.7.0/tools/csmacnz.Coveralls.exe --monocov -i ./monocovCoverage --repoToken $COVERALLS_REPO_TOKEN --commitId $TRAVIS_COMMIT --commitBranch $TRAVIS_BRANCH --commitAuthor "$REPO_COMMIT_AUTHOR" --commitEmail "$REPO_COMMIT_AUTHOR_EMAIL" --commitMessage "$REPO_COMMIT_MESSAGE" --jobId $TRAVIS_JOB_ID  --serviceName travis-ci  --useRelativePaths
