image: Visual Studio 2017

before_build:
- nuget restore

build:
  project: JimsBackgroundChanger.sln
  verbosity: minimal

test_script:
- .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\packages\*\tools\nunit3-console.exe" -targetargs:".\JimsBackgroundChanger.Tests\bin\Release\JimsBackgroundChanger.Tests.dll" -output:".\coverage.xml"
- .\packages\Codecov.1.0.1\tools\codecov.exe -f "coverage.xml" -t 4b4666f3-dbf9-4798-988e-6533df907d44