# Version format.
version: '{build}-ci'

environment:
   CoverityProjectToken:
    secure: 

init:
# Properties, passed to MSBuild project.
- ps: |
    $env:BuildDir = "$env:APPVEYOR_BUILD_FOLDER\.OUTPUT"
    $env:VersionBuild = "$env:APPVEYOR_BUILD_NUMBER"
    $env:VersionStage = "$env:APPVEYOR_REPO_BRANCH"
    $env:VersionTag = "$env:APPVEYOR_REPO_COMMIT"

image: Visual Studio 2017

platform:
- x86
- x64

configuration:
- Release

build_script:
- ps: |
    nuget restore
    $buildCmd = "msbuild.exe"
    $buildArgs = @(
      "/m",
      "/l:C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll",
      "/p:Configuration=$env:CONFIGURATION",
      "/p:Platform=$env:PLATFORM")
    # If build is not a scheduled one, then simply build the project with
    # MSBuild.
    #if ($env:APPVEYOR_SCHEDULED_BUILD -ne "True") {
    if ($env:APPVEYOR_REPO_BRANCH -ne "coverity_scan") {
      & $buildCmd $buildArgs
      return
    }

    # Else, build project with Coverity Scan.
    "Building project with Coverity..."
    & cov-build.exe --dir cov-int $buildCmd $buildArgs
    # Compress results.
    $coverityPublisher =
      ".\packages\PublishCoverity.0.11.0\tools\PublishCoverity.exe"
    "Compressing Coverity results..."
    & "$coverityPublisher" compress `
      -i "$env:APPVEYOR_BUILD_FOLDER\cov-int" `
      -o "$env:APPVEYOR_BUILD_FOLDER\$env:APPVEYOR_PROJECT_NAME.zip" `
      --overwrite

    # Upload results to Coverity server.
    $version = "$env:VersionMajor.$env:VersionMinor.$env:VersionPatch" +
      "-$env:VersionStage+$env:VersionBuild"
    "Uploading Coverity results..."
    & "$coverityPublisher" publish `
      --nologo `
      -t "$env:CoverityProjectToken" `
      -e "$env:CoverityNotificationEmail" `
      -r "$env:APPVEYOR_REPO_NAME" `
      -z "$env:APPVEYOR_BUILD_FOLDER\$env:APPVEYOR_PROJECT_NAME.zip" `
      -d "CI server branch build." `
      --codeVersion "$version"

test_script:
- .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe" -targetargs:".\JimsBackgroundChanger.Tests\bin\Release\JimsBackgroundChanger.Tests.dll" -output:".\coverage.xml"
- .\packages\Codecov.1.0.1\tools\codecov.exe -f "coverage.xml" -t 4b4666f3-dbf9-4798-988e-6533df907d44